[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install -r Requirements.txt"
]

[start]
cmd = "/app/venv/bin/python3 'Main.py- entry point'"
